[package]
name = "marketeer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.8"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
tokio = { version = "1.40", features = ["full"] }
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.0"
