[package]
name = "nonkyc-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
marketeer = { path = "../marketeer" }
tokio = { version = "1.40.0", features = ["full"] }
reqwest = "0.12.8"
serde_json = "1"
colored = "2.0"
textwrap = "0.16.0"
prettytable = "0.10.0"
ansi-str = "0.8.0"
